# Generated by Django 5.2.14 on 2026-05-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('essential', 'Essential'), ('signature', 'Signature'), ('midnight', 'Midnight')], max_length=20, unique=True, verbose_name='tier')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao_curta', models.CharField(max_length=200, verbose_name='descrição curta')),
                ('preco_desde', models.CharField(help_text="ex.: 'desde 80€' ou 'Sob consulta'", max_length=50, verbose_name='preço desde')),
                ('destaque', models.BooleanField(default=False, help_text="Marca como 'Mais popular' / flagship.", verbose_name='destaque')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ('ordem', 'tier'),
            },
        ),
        migrations.CreateModel(
            name='PedidoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('viatura', models.CharField(blank=True, max_length=100, verbose_name='viatura')),
                ('pacote_interesse', models.CharField(blank=True, choices=[('essential', 'Essential'), ('signature', 'Signature'), ('midnight', 'Midnight')], max_length=20, verbose_name='pacote de interesse')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('contactado', models.BooleanField(default=False, verbose_name='contactado')),
            ],
            options={
                'verbose_name': 'pedido de contacto',
                'verbose_name_plural': 'pedidos de contacto',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('viatura', models.CharField(blank=True, help_text="ex.: 'Porsche 911'", max_length=100, verbose_name='viatura')),
                ('texto', models.TextField(verbose_name='testemunho')),
                ('avaliacao', models.PositiveSmallIntegerField(choices=[(1, '1 / 5'), (2, '2 / 5'), (3, '3 / 5'), (4, '4 / 5'), (5, '5 / 5')], default=5, verbose_name='avaliação')),
                ('ativo', models.BooleanField(default=True, verbose_name='activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'testemunho',
                'verbose_name_plural': 'testemunhos',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='InclusaoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusoes', to='core.pacote', verbose_name='pacote')),
            ],
            options={
                'verbose_name': 'inclusão',
                'verbose_name_plural': 'inclusões',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
